name: ecolienv
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.11
  - pandas>=1.1.0
  - conda-forge::biopython
  - snakemake-minimal
  - pip>19.0
  - conda-forge::shap
  -  numpy>=1.22.0
  -  tensorflow==2.15.0
  -  pandas>=1.4.3
  -  dendropy>=4.5.2
  -  joblib
  -  seaborn>=0.12.2
  -  matplotlib>=3.7.0
  -  ete3>=3.1.1
  -  baltic
  -  scipy>=1.4.1
  -  click>=8.1.3
  - yte
  - yaml
  - natsort