model_name: "intercept"
  
# -----------------------------------------------------
# BIRTH-DEATH-SAMPLING MODEL PARAMETERS
# -----------------------------------------------------
fit_model_params:
  # Not estimated
  death_rate: 1
  sampling_mask: "data_new/sampling_mask.csv"

  # Potentially estimated
  birth_background:
    estimate: True
    penalize: False
    value: [1.000001, ]
    changepoints: []
  birth_features:
    estimate: False
    penalize: True
    states: "data_new/features_dummy.csv" # Binary features file for each sample + ancestral node
    value: 1
  sampling_features:
    estimate: False
    penalize: True
    states: "data_new/features_dummy.csv"
    value: 1
  sampling_background:
    estimate: True
    penalize: False
    value: [0.0001, 0.0001, 0.0001]
    changepoints: [2003, 2013]
  brownian_motion:
    estimate: False
    penalize: False
    value: 1
    states: "data_new/analysis/three_sampling_intervals/brownian_fit_setup.json"

# -----------------------------------------------------
# HYPERPARAMETER SEARCH SETUP
# -----------------------------------------------------
lr: .00005
n_epochs: 40000

# Values of regularization type, lambda penalty types to test
hyper_param_values:
  reg_type: ["l1"]
  # lamb: [0.5, 1, 1.5, 2]
  lamb: [0]
  sigma: [0.00000001]