model_name: "intercept"

# -----------------------------------------------------
# BIRTH-DEATH-SAMPLING MODEL PARAMETERS
# -----------------------------------------------------
fit_model_params:
  # Not estimated
  death_rate: 1
  sampling_mask: "data_new/sampling_mask.csv"

  # Potentially estimated
  birth_background:
    estimate: False
    penalize: False
    value: [1.13556701392988]
    changepoints: []
  birth_features:
    estimate: True
    penalize: True
    states: "data_new/functional_groups_corr_pastml/marginal_states.csv" # Binary features file for each sample + ancestral node
    value: 1
  sampling_features:
    estimate: True
    penalize: True
    states: "data_new/meta_features_marginal.csv"
    value: 1
  sampling_background:
    estimate: False
    penalize: False
    value: [0.0002158530500418965, 0.012898053822460863, 0.022113961151438107]
    changepoints: [2003, 2013]
  brownian_motion:
    estimate: True
    penalize: False
    value: 1
    states: "data_new/analysis/three_sampling_intervals/brownian_fit_setup.json"

# -----------------------------------------------------
# HYPERPARAMETER SEARCH SETUP
# -----------------------------------------------------
lr: .00005
n_epochs: 80000

# Values of regularization type, lambda penalty types to test
hyper_param_values:
  reg_type: ["l1"]
  # lamb: [0.5, 1, 1.5, 2]
  lamb: [1]
  sigma: [0.00000001]